### ISSUE TITLE
Allow for both measurement units

### ISSUE THREAD

**Issue by almostengr** [bitsecondal/farmosnws#14]
Allow for loading US and Metric units from the feed.

**Comment by almostengr** [comment]
Set the default value to both units.

**Comment by almostengr** [comment]
Set the default value to both units.

**Comment by mstenta** [comment]
The "Farm Quantity" (farm_quantity) module that comes with farmOS allows users to select their default system of measurement (metric vs us/imperial) during farmOS installation. That setting is available via the `farm_quantity_unit_system` variable. If you need to provide a way for the user to select the system, it would be best to standardize on the farmOS core variable. Although maybe you need to do more than that as well. Figured I would at least point that out in case you weren't aware of it! :-)

**Comment by almostengr** [comment]
I was aware of that variable. I had already built that part of the module when I discovered it.  I may consider switching to using the core variable.

**Comment by almostengr** [comment]
Has been implemented to use farm_quantity_unit_system variable for metric or imperial variables.
