### ISSUE TITLE
Link on farmOS.org

### ISSUE THREAD

**Issue by mstenta** [bitsecondal/farmosnws#4]
Hi @bitsecondal ! Thanks for creating this module!

Would you like me to add a link to it on farmOS.org?

It would appear under "Other modules" on this page: http://farmos.org/development/projects/

I would be happy to add your name/organization to the list of farmOS supporters too, if you'd like: http://farmos.org/community/supporters/

**Comment by almostengr** [comment]
@mstenta Yes link can be placed on the FarmOS website.

Please use "Kenny Robinson" is the individual name to be listed on the website.

**Comment by mstenta** [comment]
Done! Thanks again for the contributions!
